/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DOCTOR_REPORT_R1_V2;

import static DOCTOR_REPORT_R1_V2.LoginMain.LoginCono;
import static DOCTOR_REPORT_R1_V2.LoginMain.LoginDivision;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.chrono.ThaiBuddhistDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mahakit
 */
public class ReportPrinted extends javax.swing.JFrame {

    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
    SimpleDateFormat format2 = new SimpleDateFormat("yyyyMMdd", Locale.ENGLISH);
    DefaultTableModel model1;
    String selectednum = new String();
    Date chosedate = ReportDoctorLocal.chosendate;
    Integer amounttick = 0;

    /**
     * Creates new form ReportPrinted
     */
    public ReportPrinted() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage("icon.png"));
        this.setTitle("Company  " + LoginMain.LoginCompanyName);
        model1 = (DefaultTableModel) jTable1.getModel();
        lblCompanyName.setText(LoginMain.LoginCompanyName);
        showingdate.setText("Chosen Date: " + format.format(ReportDoctorLocal.chosendate));
        getPrinted();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompanyName = new java.awt.Label();
        showingdate = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxSelectAll = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCancel = new java.awt.Button();
        buttonPrint = new java.awt.Button();
        jButtonRefresh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        documentfoundnum = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCompanyName.setAlignment(java.awt.Label.CENTER);
        lblCompanyName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCompanyName.setForeground(new java.awt.Color(204, 0, 0));
        lblCompanyName.setText("Company Name");

        showingdate.setAlignment(java.awt.Label.CENTER);
        showingdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showingdate.setForeground(new java.awt.Color(51, 102, 255));
        showingdate.setText("Date");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PRINTED DOCUMENT");

        jCheckBoxSelectAll.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBoxSelectAll.setText("Select All");
        jCheckBoxSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSelectAllActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Deliverer Detail", "CO No.", "Inv No.", "Customer Code", "Customer Name", "Date", "Print"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(6).setMinWidth(40);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(40);
        }

        btnCancel.setBackground(new java.awt.Color(240, 240, 240));
        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 0, 0));
        btnCancel.setLabel("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        buttonPrint.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonPrint.setLabel("Print");
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });

        jButtonRefresh.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRefresh.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonRefresh.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRefresh.setText("Refresh");
        jButtonRefresh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Found:");

        documentfoundnum.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        documentfoundnum.setForeground(new java.awt.Color(0, 0, 0));
        documentfoundnum.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(documentfoundnum, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199)
                        .addComponent(showingdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxSelectAll)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 352, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(335, 335, 335))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(jCheckBoxSelectAll)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonRefresh)
                                    .addComponent(showingdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(documentfoundnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        CheckRemark();

        //        MouseListener();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.show(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void jCheckBoxSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSelectAllActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxSelectAll.isSelected()) {
            for (int i = 0; i <= model1.getRowCount() - 1; i++) {
                model1.setValueAt(true, i, 6);
            }
        } else {
            for (int i = 0; i <= model1.getRowCount() - 1; i++) {
                model1.setValueAt(false, i, 6);
            }
        }
        CheckRemark();
    }//GEN-LAST:event_jCheckBoxSelectAllActionPerformed

    private Boolean getDuplicateCO(String conumber) {

        try {

            Connection conn = ConnectDB2.ConnectionDB();
            Statement sta = conn.createStatement();

            String Sql = "SELECT COUNT(*) AS COUNT  \n"
                    + "FROM BRLDTA0100.INVCNRN1 \n"
                    + "WHERE INCONO = '" + LoginCono + "' \n"
                    + "AND INORNO = '" + conumber + "'";

            ResultSet rs = sta.executeQuery(Sql);

            while (rs.next()) {
                int count = rs.getInt("COUNT");
                if (count > 0) {
                    return true;
                }

            }
            rs.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        return false;

    }
    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
        // TODO add your handling code here:
        ClassGetReport cgr = new ClassGetReport();
        boolean lastrow = false;
        //how many times that was ticked to check
        Integer printtimes = 0;
        buttonPrint.setEnabled(false);
        //check the amount ticked again or refreshing
        Amounttick();
        for (int i = 0; i <= model1.getRowCount() - 1; i++) {
            Boolean print = (Boolean) model1.getValueAt(i, 6);

            if (print == null) {
                print = false;
            }
            if (print) {

                String printedinvoice = (model1.getValueAt(i, 1)).toString();
                boolean coDuplicate = getDuplicateCO(printedinvoice);
                System.out.println(coDuplicate);

                if (coDuplicate) {
                    printtimes++;
                    String StartDate = new String();
                    System.out.println(java.time.LocalDate.now());
                    if (StartDate.isEmpty()) {
                        StartDate = (java.time.LocalDate.now()).toString();
                    } else {
                        StartDate = model1.getValueAt(i, 5).toString().trim();
                    }
                    LocalDate localdate = LocalDate.parse(StartDate);
                    ThaiBuddhistDate thDate = ThaiBuddhistDate.from(localdate);

                    String year = thDate.toString().substring(16, 20);
                    String subYear = thDate.toString().substring(18, 20);
                    if (printtimes == amounttick) {
                        lastrow = true;
                        System.out.println("statement true");
                    }

                    cgr.GetReportDoctorLocal(printedinvoice, year, lastrow);

                } else {
                    JOptionPane.showMessageDialog(null, "CO not found.");

                }

            }

        }
    }//GEN-LAST:event_buttonPrintActionPerformed

    private void Amounttick() {
        amounttick = 0;

        buttonPrint.setEnabled(false);

        for (int o = 0; o <= model1.getRowCount() - 1; o++) {

            Boolean print = (Boolean) model1.getValueAt(o, 6);

            if (print == null) {
                print = false;
            }

            if (print) {
                buttonPrint.setEnabled(true);
                amounttick++;
            } else {
                buttonPrint.setEnabled(false);
            }
        }

    }
    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here
        System.out.println(new JFileChooser().getFileSystemView().getDefaultDirectory().toString());
        getPrinted();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    //เอาข้อมูลเอกสารที่ปริ้นไปแล้ว
    private void CheckRemark() {

        buttonPrint.setEnabled(false);
        for (int i = 0; i <= model1.getRowCount() - 1; i++) {

            Boolean print = (Boolean) model1.getValueAt(i, 6);

            if (print == null) {
                print = false;
            }

            if (print) {
                buttonPrint.setEnabled(true);
                break;
            } else {
                buttonPrint.setEnabled(false);
            }
        }

    }

    private void getPrinted() {
//        Runnable runnable = new Runnable() {
//        public void run() {
//                jButton1.setEnabled(false);
        try {

            while (model1.getRowCount() > 0) {
                for (int i = 0; i < model1.getRowCount(); ++i) {
                    model1.removeRow(i);
                }
            }

            Connection conn = ConnectDB2.ConnectionDB();
            Statement sta = conn.createStatement();

            String Sql = "SELECT IFNULL(b.DCTX40,' ') AS DCTX40 ,a.*\n"
                    + "FROM \n"
                    + "(SELECT DISTINCT INCONO, INDIVI, INORNO, INIVNO,OACUNO,OKCUNM, INRNNO, COALESCE(INDATE,0) AS INDATE\n"
                    + "FROM m3fdbprd.OOHEAD a, m3fdbprd.OCUSMA b, BRLDTA0100.INVCNRN1 c, M3FDBPRD.ODLINE d\n"
                    + "WHERE b.OKCONO = a.OACONO \n"
                    + "AND b.OKCUNO = a.OACUNO\n"
                    + "AND c.INORNO = a.OAORNO \n"
                    + "AND c.INDATE = '" + format2.format(chosedate) + "' \n"
                    + "AND d.UBORNO = c.INORNO\n"
                    + "AND d.UBITNO NOT IN ('WA004000500', 'PA033001000')\n"
                    + "ORDER BY INDATE\n"
                    + ") AS a\n"
                    + "LEFT JOIN \n"
                    + "(SELECT A.*,C.DCTX40\n"
                    + "FROM(\n"
                    + "select card_upc ,card_carno,card_meth,card_date,a.caro_orno,card_cord,card_cspe,OACONO,OADIVI,OAORNO\n"
                    + "FROM brldta0100.sal_cardel,brldta0100.sal_carord a,M3FDBPRD.OOHEAD\n"
                    + "Where card_date = a.CARO_DATE\n"
                    + "--where card_date IN  (20210704,20210711,20210718,20210725,20210801,20210808,20210815,20210822,20210829,20210905,20210912\n"
                    + "--,20210919,20210926,20211003,20211010)\n"
                    + "--and card_cord <> '0'\n"
                    + "--and card_carno not in (--'TK000030','TK000031','TK000032','TK000033')\n"
                    + "--and card_tearm NOT IN  ('N','C')\n"
                    + "--and card_date between 20210416 AND 20230616\n"
                    + "AND card_meth = a.CARO_METH\n"
                    + "AND card_carno = a.caro_carno\n"
                    + "AND a.caro_orno = oaorno\n"
                    + "--AND oacuno ='TH01010088'\n"
                    + "--AND card_meth <='102'\n"
                    + "AND oacono =10\n"
                    + "--AND oacuno IN ('TH75050004')\n"
                    + "--group by card_upc,card_carno,card_meth, DCTX40\n"
                    + ") A\n"
                    + "LEFT  JOIN M3FDBPRD.dcarri AS C ON C.DCTRCA = A.CARD_CARNO AND C.dccono =10\n"
                    + "ORDER BY CARD_DATE) AS b\n"
                    + "ON b.OAORNO = a.INORNO AND b.OACONO = a.INCONO";

//            String Sql = "SELECT INCONO, INDIVI, INORNO, INIVNO,OACUNO,OKCUNM, INRNNO, COALESCE(INDATE,0) AS INDATE  \n"
//                    + "FROM m3fdbprd.OOHEAD a, m3fdbprd.OCUSMA b, BRLDTA0100.INVCNRN1 c\n"
//                    + "WHERE b.OKCONO = a.OACONO \n"
//                    + "AND b.OKCUNO = a.OACUNO\n"
//                    + "AND c.INORNO = a.OAORNO \n"
//                    + "AND c.INDATE = '" + format2.format(chosedate) + "' \n"
//                    + "ORDER BY INDATE";
            ResultSet rs = sta.executeQuery(Sql);

            while (rs.next()) {
                if (rs.getString("INDATE").trim().equals("0")) {
                    //comment ใช้ให้ขึ้น 00001-01-01
                    //String getDate = "0";
                    //Date cvDate = new SimpleDateFormat("yyyymmdd").parse("0001-01-01");
                    model1.insertRow(model1.getRowCount(), new Object[]{
                        rs.getString("DCTX40").trim(),
                        rs.getString("INORNO").trim(),
                        rs.getString("INIVNO").trim(),
                        rs.getString("OACUNO").trim(),
                        rs.getString("OKCUNM").trim(), //format.format(cvDate),
                    });

                } else {

                    String getDate = rs.getString("INDATE").trim();
                    Date cvDate = new SimpleDateFormat("yyyyMMdd").parse(getDate);
                    model1.insertRow(model1.getRowCount(), new Object[]{
                        rs.getString("DCTX40").trim(),
                        rs.getString("INORNO").trim(),
                        rs.getString("INIVNO").trim(),
                        rs.getString("OACUNO").trim(),
                        rs.getString("OKCUNM").trim(),
                        format.format(cvDate),});

                }

                //System.out.println(cvDate);
                //format.format(getDate),});
                documentfoundnum.setText(Integer.toString(model1.getRowCount()) + " Document(s)");
            }
            rs.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
//                jButton1.setEnabled(true);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportPrinted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportPrinted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportPrinted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportPrinted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportPrinted().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnCancel;
    private java.awt.Button buttonPrint;
    private java.awt.Label documentfoundnum;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JCheckBox jCheckBoxSelectAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label lblCompanyName;
    private java.awt.Label showingdate;
    // End of variables declaration//GEN-END:variables

    private Object getValueAt(int i, int selectedColumn) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
