/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DOCTOR_REPORT_R1_V2;

import static DOCTOR_REPORT_R1_V2.LoginMain.LoginUsername;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jilasak
 */
public class SetSeries extends javax.swing.JFrame {

    /**
     * Creates new form SetSeries
     */
    public SetSeries() {
        initComponents();
        this.setTitle("Set Series");
        callSeries();

    }

    public void callSeries() {
        try {
            Connection conn = ConnectDB2.ConnectionDBS();
            Statement sta = conn.createStatement();
            String sql = "SELECT A.ROWPRENUM,B.PDR_START ,B.PDR_END , CASE WHEN B.PDR_PROGRAM = 'THAIMAX' THEN B.PDR_CODE || '/' || B.PDR_YEAR || '/'  || 'THMAX' ||TRIM(TO_CHAR(A.ROWPRENUM,'000000')) \n"
                    + "WHEN B.PDR_PROGRAM = 'Farm' THEN B.PDR_CODE || '/' || B.PDR_YEAR || '/'  || 'F' ||TRIM(TO_CHAR(A.ROWPRENUM,'000000')) ELSE\n"
                    + "B.PDR_CODE || '/' || B.PDR_YEAR || '/'  || TRIM(TO_CHAR(A.ROWPRENUM,'000000')) END AS RUNNING\n"
                    + ",B.PDR_CODE, B.PDR_YEAR, B.PDR_START, B.PDR_END\n"
                    + "FROM BRLDTA0100.ROW_PREREPORT A,BRLDTA0100.PRODOCRUNNING B\n"
                    + "WHERE A.ROWPRENUM BETWEEN int(B.PDR_START) AND int(B.PDR_END) \n"
                    + "AND B.PDR_CONO = '10'\n"
                    + "AND B.PDR_DIVI = '101'\n"
                    + "AND B.PDR_USER = '" + LoginMain.LoginUsername.trim() + "'\n"
                    + "AND B.PDR_PROGRAM =  '" + LoginMain.ProgramName.trim() + "' \n"
                    + "ORDER BY RUNNING DESC  \n"
                    + "LIMIT 1 ";
            ResultSet rsl = sta.executeQuery(sql);
            while (rsl.next()) {
                txt_code.setText(rsl.getString("PDR_CODE").trim());
                txt_year.setText(rsl.getString("PDR_YEAR").trim());
//                txt_month.setText(rsl.getString("PDR_MONTH").trim());
                txt_start.setText(rsl.getString("PDR_START").trim());
                txt_end.setText(rsl.getString("PDR_END").trim());
                txt_sample.setText(rsl.getString("RUNNING").trim());
            }

        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_end = new javax.swing.JTextField();
        txt_start = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_year = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_code = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_sample = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_set = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        btn_print1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        txt_end.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        getContentPane().add(txt_end);
        txt_end.setBounds(160, 180, 140, 40);

        txt_start.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        getContentPane().add(txt_start);
        txt_start.setBounds(20, 180, 130, 40);

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Sample :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 220, 130, 30);

        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("End");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 150, 130, 30);

        txt_year.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        getContentPane().add(txt_year);
        txt_year.setBounds(160, 110, 140, 40);

        jLabel4.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 255));
        jLabel4.setText("Year");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 80, 130, 30);

        txt_code.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        getContentPane().add(txt_code);
        txt_code.setBounds(20, 110, 130, 40);

        jLabel5.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 255));
        jLabel5.setText("Code");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 80, 130, 30);

        txt_sample.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        getContentPane().add(txt_sample);
        txt_sample.setBounds(20, 250, 430, 60);

        jLabel6.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 255));
        jLabel6.setText("Start");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 150, 130, 30);

        jLabel7.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Doctor Report Set Series");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 10, 450, 60);

        btn_set.setText("Set");
        btn_set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setActionPerformed(evt);
            }
        });
        getContentPane().add(btn_set);
        btn_set.setBounds(320, 180, 130, 40);

        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        getContentPane().add(btn_print);
        btn_print.setBounds(20, 320, 140, 40);

        btn_print1.setText("Print W/O Series");
        btn_print1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_print1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_print1);
        btn_print1.setBounds(170, 320, 150, 40);

        setSize(new java.awt.Dimension(487, 422));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setActionPerformed
        String code = txt_code.getText().trim();
        String year = txt_year.getText().trim();
//        String month = txt_month.getText().trim();
        String start = txt_start.getText().trim();
        String end = txt_end.getText().trim();
//        month = String.format("%02d", Integer.parseInt(month)); // Filling with zeroes  

        try {
            Connection conn = ConnectDB2.ConnectionDBS();
            Statement sta = conn.createStatement();

            String sql = "UPDATE BRLDTA0100.PRODOCRUNNING\n"
                    + "SET PDR_CODE = '" + code + "', PDR_YEAR = '" + year + "', PDR_START = '" + start + "', PDR_END = '" + end + "' \n"
                    + "where UPPER(PDR_USER) = UPPER('" + LoginMain.LoginUsername.trim() + "')   and PDR_PROGRAM = '" + LoginMain.ProgramName.trim() + "' ";
            System.err.println(sql);
            sta.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Complete !");
            callSeries();
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }


    }//GEN-LAST:event_btn_setActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed

        btn_print.enable(false);
        ClassGetReport cgr = new ClassGetReport();
        cgr.getReportSetSeries(LoginMain.ProgramName);
        btn_print.enable(true);

    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_print1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_print1ActionPerformed
        // TODO add your handling code here:
        btn_print.enable(false);
        ClassGetReport cgr = new ClassGetReport();
        cgr.getReportSetSeriesV2(LoginMain.ProgramName);
        btn_print.enable(true);
    }//GEN-LAST:event_btn_print1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetSeries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_print;
    public static javax.swing.JButton btn_print1;
    private javax.swing.JButton btn_set;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_code;
    private javax.swing.JTextField txt_end;
    private javax.swing.JTextField txt_sample;
    private javax.swing.JTextField txt_start;
    private javax.swing.JTextField txt_year;
    // End of variables declaration//GEN-END:variables
}
